In [42]:
import pandas as pd
data = {
    "name": ["Umer", "Ali", "Sara", "John"],
    "age": [21, 22, 20, 23],
    "marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print(df)

   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88

In [43]:
df.query("marks==marks.max()")
df[df['marks']==df['marks'].max()]

df.sort_values('marks').tail(1)

  name  age  marks
1  Ali   22     90

In [44]:
df[df['marks']==df["marks"].max()]

  name  age  marks
1  Ali   22     90

In [45]:
df

   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88

In [46]:
df[df['marks']>df['marks'].mean()]

   name  age  marks
1   Ali   22     90
3  John   23     88

In [47]:
df[df['marks']==df['marks'].max()]

  name  age  marks
1  Ali   22     90

In [48]:
df.sort_values("marks").head(1)

   name  age  marks
2  Sara   20     78

In [49]:
df.sort_values('marks').tail(1)

  name  age  marks
1  Ali   22     90

In [50]:
df.query("marks == marks.max()")

  name  age  marks
1  Ali   22     90

In [51]:
df.sort_values("marks").head(1)

   name  age  marks
2  Sara   20     78

In [52]:
df[df["marks"]==df['marks'].min()]

   name  age  marks
2  Sara   20     78

In [53]:
df["marks"]=df["marks"].apply(lambda x:x*2)

In [54]:
df[df["marks"]>200]

Empty DataFrame
Columns: [name, age, marks]
Index: []

In [55]:
df["marks"]=[100,200,300,500]

In [56]:
df.to_csv("a.csv",index=False)

In [57]:
df["marks"].mean()
df["marks"].sum()

np.int64(1100)

In [58]:
df["age"]=df["age"]+4

In [59]:
df.drop('age',axis=1,inplace=True)

In [60]:
df

   name  marks
0  Umer    100
1   Ali    200
2  Sara    300
3  John    500

In [4]:
# df[df["age"]>20]

In [ ]:
df[(df["marks"]>85) & (df["age"]>20)]

   name  age  marks
1   Ali   22     90
3  John   23     88

In [ ]:
print(df.head())   # first rows
print(df.tail())   # last rows
print(df.shape)    # (rows, columns)
print(df.columns)  # column names
print(df.info())   # full info

   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88
   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88
(4, 3)
Index(['name', 'age', 'marks'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None

In [ ]:
df["grade"]

   name  age  marks
3  John   23     88

In [ ]:
df.isnull().sum()

name     0
age      0
marks    0
dtype: int64

In [ ]:
df["age"].fillna(df['marks'].mean())

0    21
1    22
2    20
3    23
Name: age, dtype: int64

In [ ]:
df.fillna(df['age'].mean(),inplace=True)
df.dropna(inplace=True)

In [66]:
df.drop_duplicates(inplace=True)

In [73]:
df['marks']=df['marks'].astype(int)

In [74]:
df

   name  marks
0  Umer    100
1   Ali    200
2  Sara    300
3  John    500

In [78]:
pd.merge(df,df,on="marks")

  name_x  marks name_y
0   Umer    200   Umer
1    Ali    400    Ali
2   Sara    600   Sara
3   John   1000   John

In [75]:
df['marks']=df['marks'].apply(lambda x:x*2)
df

   name  marks
0  Umer    200
1   Ali    400
2  Sara    600
3  John   1000

In [79]:
df1=df2=df

In [ ]:

pd.merge(df1, df2, how="inner")
pd.merge(df1, df2, how="left")
pd.merge(df1, df2, how="right")

   name  marks
0  Umer    200
1   Ali    400
2  Sara    600
3  John   1000

In [83]:
df1 = pd.DataFrame({
    "id": [1,2],
    "name": ["Umer","Ali"]
})

df2 = pd.DataFrame({
    "id": [1,2],
    "marks": [90,85]
})

In [84]:
df1

   id  name
0   1  Umer
1   2   Ali

In [85]:
df2

   id  marks
0   1     90
1   2     85

In [92]:
pd.merge(df1, df2, how="left")

   id  name  marks
0   1  Umer     90
1   2   Ali     85

In [93]:

pd.merge(df1, df2, how="right")

   id  name  marks
0   1  Umer     90
1   2   Ali     85

In [91]:
pd.merge(df1, df2, how="inner")

   id  name  marks
0   1  Umer     90
1   2   Ali     85

In [88]:
pd.merge(df1,df2)

   id  name  marks
0   1  Umer     90
1   2   Ali     85

In [7]:
pd.pivot_table(df, values="marks", index="grade", aggfunc="mean")

       marks
grade
A      92.25

In [97]:
df

   name  marks
0  Umer    200
1   Ali    400
2  Sara    600
3  John   1000

In [99]:
df['grade']=df['marks'].apply(lambda x:"A" if x>df['marks'].mean() else "B")
df

   name  marks grade
0  Umer    200     B
1   Ali    400     B
2  Sara    600     A
3  John   1000     A

In [100]:
df.sort_values('marks',ascending=False)

   name  marks grade
3  John   1000     A
2  Sara    600     A
1   Ali    400     B
0  Umer    200     B

In [101]:
df['grade'].value_counts()

grade
B    2
A    2
Name: count, dtype: int64

In [103]:
import pandas as pd

data = {
    "name": ["Umer", "Ali", "Sara", "John", "Aman"],
    "department": ["CS", "CS", "IT", "IT", "CS"],
    "marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)
print(df)

   name department  marks
0  Umer         CS     85
1   Ali         CS     90
2  Sara         IT     78
3  John         IT     88
4  Aman         CS     95

In [122]:
df.groupby("department")["marks"].mean().reset_index()

  department  marks
0         CS   90.0
1         IT   83.0

In [118]:
df.groupby('department')['marks'].max()

department
CS    95
IT    88
Name: marks, dtype: int64

In [112]:
df.groupby('department')['marks'].mean()

department
CS    90.0
IT    83.0
Name: marks, dtype: float64

In [113]:
df.groupby('department')['marks'].mean()

department
CS    90.0
IT    83.0
Name: marks, dtype: float64

In [114]:
x=df.groupby('department')
x['marks'].mean()

df.groupby("department")["marks"].count()

department
CS    3
IT    2
Name: marks, dtype: int64

In [104]:
df['department'].value_counts()

department
CS    3
IT    2
Name: count, dtype: int64

In [6]:
# REVISION
# =========================================
# 1. IMPORT
# =========================================
import pandas as pd

# =========================================
# 2. CREATE DATAFRAME
# =========================================

data = {
    "name": ["Umer", "Ali", "Sara", "John"],
    "age": [21, 22, 20, 23],
    "marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)
print(df)

# =========================================
# 3. BASIC INFO
# =========================================

print(df.head())     # first rows
print(df.tail())     # last rows
print(df.shape)      # (rows, cols)
print(df.columns)    # column names
print(df.info())     # full info
print(df.describe()) # stats

# =========================================
# 4. SELECT DATA
# =========================================

print(df["name"])                 # single column
print(df[["name", "marks"]])      # multiple columns

print(df.iloc[0])                 # row by index
print(df.iloc[0,1])               # specific value

# =========================================
# 5. FILTERING (VERY IMPORTANT)
# =========================================

print(df[df["marks"] > 80])

print(df[(df["marks"] > 80) & (df["age"] > 21)])

# =========================================
# 6. ADD / MODIFY COLUMN
# =========================================

df["grade"] = ["B", "A", "C", "B"]

df["marks"] = df["marks"] + 5

# =========================================
# 7. DROP
# =========================================

df.drop("age", axis=1, inplace=True)

# =========================================
# 8. SORTING
# =========================================

print(df.sort_values("marks", ascending=False))

# =========================================
# 9. GROUPBY (VERY IMPORTANT)
# =========================================

print(df.groupby("grade")["marks"].mean())

# multiple aggregation
print(df.groupby("grade")["marks"].agg(["mean","max","min"]))

# =========================================
# 10. HANDLE MISSING VALUES
# =========================================

df.isnull()
df.fillna(0)
df.dropna()

# =========================================
# 11. APPLY
# =========================================

df["marks"] = df["marks"].apply(lambda x: x + 2)

# =========================================
# 12. VALUE COUNTS
# =========================================

print(df["grade"].value_counts())

# =========================================
# 13. MIN / MAX ROW (IMPORTANT)
# =========================================

print(df.loc[df["marks"].idxmin()])     # best method
print(df.nsmallest(1, "marks"))

# =========================================
# 14. MERGE / JOIN (VERY IMPORTANT)
# =========================================

df1 = pd.DataFrame({
    "id": [1,2],
    "name": ["Umer","Ali"]
})

df2 = pd.DataFrame({
    "id": [1,2],
    "marks": [90,85]
})

merged = pd.merge(df1, df2, on="id")
print(merged)

# =========================================
# 15. PIVOT TABLE
# =========================================

print(pd.pivot_table(df, values="marks", index="grade", aggfunc="mean"))

# =========================================
# 16. CORRELATION (ML IMPORTANT)
# =========================================

# print(df.corr())

# =========================================
# 17. SAVE & LOAD
# =========================================

df.to_csv("data.csv", index=False)

df = pd.read_csv("data.csv")

# =========================================
# 🔥 REAL WORKFLOW (ML PIPELINE STYLE)
# =========================================

df = pd.read_csv("data.csv")

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

df["grade"] = df["marks"].apply(lambda x: "A" if x > 80 else "B")

print(df.groupby("grade")["marks"].mean())

print(df.sort_values("marks", ascending=False))

# =========================================
# DONE ✅
# =========================================

   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88
   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88
   name  age  marks
0  Umer   21     85
1   Ali   22     90
2  Sara   20     78
3  John   23     88
(4, 3)
Index(['name', 'age', 'marks'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None
             age      marks
count   4.000000   4.000000
mean   21.500000  85.250000
std     1.290994   5.251984
min    20.000000  78.000000
25%    20.750000  83.250000
50%    21.500000  86.500000
75%    22.250000  88.500000
max    23.000000  90.000000
0    Umer
1     Ali
2    Sara
3    John
Name: name, dtype: str
   name  marks
0  Umer     85
1   Ali     90
2  Sara     78
3  John     88
name     Umer
age        21
marks      85
Name: 0, dtype: object
21
   name  age  marks
0  Umer   21     85
1   Ali   22     90
3  John   23     88
   name  age  marks
1   Ali   22     90
3  John   23     88
   name  marks grade
1   Ali     95     A
3  John     93     B
0  Umer     90     B
2  Sara     83     C
grade
A    95.0
B    91.5
C    83.0
Name: marks, dtype: float64
       mean  max  min
grade
A      95.0   95   95
B      91.5   93   90
C      83.0   83   83
grade
B    2
A    1
C    1
Name: count, dtype: int64
name     Sara
marks      85
grade       C
Name: 2, dtype: object
   name  marks grade
2  Sara     85     C
   id  name  marks
0   1  Umer     90
1   2   Ali     85
       marks
grade
A       97.0
B       93.5
C       85.0
grade
A    92.25
Name: marks, dtype: float64
   name  marks grade
1   Ali     97     A
3  John     95     A
0  Umer     92     A
2  Sara     85     A